name: Go package
on: [push]
jobs:
  build:
    name: 'Go Build (1.20)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build ./...
  static:
    name: 'Go Static (1.20)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: 'go install honnef.co/go/tools/cmd/staticcheck@latest'
      - run: 'go vet ./...'
      - run: 'staticcheck ./...'
  test:
    name: 'Go Test (1.20)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: go get .
      - name: Test
        run: go test ./...
